In [2]:
import numpy as np

n1 = np.array([1,2,3])
print(n1)

[1 2 3]


In [27]:
n2 = np.array([[1,2],[3,4] ])

In [4]:
n3 = np.array( [[[1,2], [3,4]], [[1,2], [3,4]], ] )
n3

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [3, 4]]])

In [16]:
range(0,5,1) # 증가치는 정수만 지원

range(0, 5)

In [17]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
np.linspace(1, 10, 6)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [19]:
np.ones([2,2,3])  # 3차원의 경우는 면, 행 열 이다.

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [20]:
%whos

Variable   Type       Data/Info
-------------------------------
n1         ndarray    3: 3 elems, type `int32`, 12 bytes
n3         ndarray    2x2x2: 8 elems, type `int32`, 32 bytes
np         module     <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
x          range      range(0, 5)


In [25]:
n1.ndim , n1.shape, n1.size

(1, (3,), 3)

In [26]:
n3.ndim, n3.shape, n3.size

(3, (2, 2, 2), 8)

In [28]:
n2.T

array([[1, 3],
       [2, 4]])

In [30]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
# arr1.reshape(2,3,2)
arr1.reshape(-1,3,2) # -1은 적절하게 단한번만 알아서 나타내줌. (즉 나누기 귀찮을 때 -1 로 하면 됨.)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [39]:
arr1.reshape(2,3,-1).reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
arr2 = arr1.reshape(2,3,-1)
arr2

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [41]:
arr2.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [42]:
arr2.reshape(1,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [43]:
arr2.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
n11 = np.arange(1,5).reshape(2,2)
n11

array([[1, 2],
       [3, 4]])

In [45]:
n22 = np.arange(10, 14).reshape(2,2)
n22

array([[10, 11],
       [12, 13]])

In [46]:
n11+n22

array([[11, 13],
       [15, 17]])

In [47]:
점수 = np.array( [1,3,5,9,10] )
구분 = np.array( ['Fail','Fail','Fail','Pass','Pass'] )

In [52]:
내점수 = 8 
print(점수 - 내점수)
dists = 점수 - 내점수
print(dists**2)
print(np.abs(dists))
dists = dists**2
print(dists)


[-7 -5 -3  1  2]
[49 25  9  1  4]
[7 5 3 1 2]
[49 25  9  1  4]


In [56]:
좌표리스트 = np.array([
    [1, 5],
    [2, 10],
    [3, 6],
    [4, 2],
    [5, 3],
    [7, 3],
])
구분 = np.array(["Fail","Fail","Fail","Pass","Pass","Pass"])

In [59]:
내좌표 = [5, 5]
dists = 좌표리스트 - 내좌표   # numpy에서만 지원.

In [60]:
dists = dists**2
dists

array([[16,  0],
       [ 9, 25],
       [ 4,  1],
       [ 1,  9],
       [ 0,  4],
       [ 4,  4]], dtype=int32)

In [66]:
dists.sum() # 이렇게 더하면 모든 요소들을 다 더한 것.
np.sum(dists) # 이것도 더하면 모든 요소들을 다 더한 것.
print(np.sum(dists, axis=1)) #  axis가 1이면 행별로 값을 더해서 나타내준다. 즉 열방향 
print(np.sqrt(np.sum(dists, axis=1)))

[16 34  5 10  4  8]
[4.         5.83095189 2.23606798 3.16227766 2.         2.82842712]


In [68]:
지점별매출리스트 = np.array([
    [1, 5, 3, 3],  # 주류, 식품, 영업매출, 개발매출
    [2, 10, 4, 4],
    [3, 6, 7, 7],
    [4, 2, 7, 7],
])
구분 = np.array(["경고","경고", "경고","승진", ])

나의매출 = [2, 3, 5, 5] 

In [78]:
arr3 = np.sqrt(((지점별매출리스트 - 나의매출)**2).sum(axis=1))
arr3

array([3.60555128, 7.14142843, 4.24264069, 3.60555128])

In [81]:
print(arr3 < 4)
print(지점별매출리스트[arr3 < 4]) # 참인 행들이 출력 // 첫번째 행과 3번째 행이 True여서 나오게 되고, 행의 개수만큼 참거짓이 들어가야 나옴.



[ True False False  True]
[[1 5 3 3]
 [4 2 7 7]]


In [77]:
print(지점별매출리스트[0])
print(지점별매출리스트[0][0])
print(지점별매출리스트[0,0])
print(지점별매출리스트[:,0]) # 행, 열  ( 내용을 접근하는 방법을 인덱싱이라고 한다. )


[1 5 3 3]
1
1
[1 2 3 4]


In [87]:
print(지점별매출리스트)
지점별매출리스트[[0,1], [1,1]]
지점별매출리스트[2:4,2:4]

[[ 1  5  3  3]
 [ 2 10  4  4]
 [ 3  6  7  7]
 [ 4  2  7  7]]


array([[7, 7],
       [7, 7]])

In [88]:
np.where(지점별매출리스트%2==0)

(array([1, 1, 1, 1, 2, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 1, 0, 1], dtype=int64))

In [90]:
arr4 = np.where(지점별매출리스트<4, "경고", "유예")
arr4    # dtype이 U2면, 데이터 타입이 Unit코드이고, 최대길이가 2다.(경고, 유예 둘다 2자리) 

array([['경고', '유예', '경고', '경고'],
       ['경고', '유예', '유예', '유예'],
       ['경고', '유예', '유예', '유예'],
       ['유예', '경고', '유예', '유예']], dtype='<U2')

In [91]:
arr4 = np.where(지점별매출리스트<4, "Warning", "Remain")
arr4 

array([['Warning', 'Remain', 'Warning', 'Warning'],
       ['Warning', 'Remain', 'Remain', 'Remain'],
       ['Warning', 'Remain', 'Remain', 'Remain'],
       ['Remain', 'Warning', 'Remain', 'Remain']], dtype='<U7')

In [100]:
지점명 = list("ABCD")
print(지점명)
print("".join(지점명))
# 문자열을 쪼개서 배열로 담고싶을 때 이렇게 하면 됨.


['A', 'B', 'C', 'D']
ABCD


In [104]:
# 주류, 식품, 영업매출, 개발매출
print(지점별매출리스트)
지점명 = np.array(list("ABCD"))

[[ 1  5  3  3]
 [ 2 10  4  4]
 [ 3  6  7  7]
 [ 4  2  7  7]]


In [94]:
지점별매출리스트.min(axis=0)

array([1, 2, 3, 3])

In [107]:
# 최소값의 인덱스 : argmin , 최대값의 인덱스 : argmax
min_index = 지점별매출리스트[:,0].argmin()
지점명[min_index]

'A'

In [109]:
지점별매출리스트[:, 0].mean()
np.quantile(지점별매출리스트[:,0], 0.25)  # 25%

1.75

In [111]:
print(지점별매출리스트[: , 1])
print(np.sort(지점별매출리스트[: , 1]) )

[ 5 10  6  2]
[ 2  5  6 10]


In [113]:
aa= np.array([3,1,7,9])
print(aa)
sort_index = np.argsort(aa)
print(sort_index)
print(aa[sort_index])

[3 1 7 9]
[1 0 2 3]
[1 3 7 9]


In [131]:
좌표리스트 = np.array([
    [1, 5],  # x, y
    [2, 10],
    [3, 6],
    [4, 2],
    [5, 3],
    [7, 3],
])
구분 = np.array(["Fail","Fail","Fail","Pass","Pass","Pass",])

내좌표 = [5,5]
dists = 좌표리스트 - 내좌표
print("내좌표와 좌표들간 거리", dists)
dists = dists**2
print("거리를 각각 제곱",dists)
dists = np.sqrt(np.sum(dists, axis=1))    # 내좌표와 좌표리스트간 직선 거리
print("제곱들을 더해 제곱근(직선거리)",dists)
# 직선거리를 정렬
sort_index = np.argsort(dists)
print("가장 가까이 배치되어야할 순서 인덱스", sort_index)
print(구분[sort_index])
print("결론: 나의 예측", 구분[sort_index][0])
# 범위를 넓혀 가장 가까운 3개를 추출
print(구분[sort_index][:3])

내좌표와 좌표들간 거리 [[-4  0]
 [-3  5]
 [-2  1]
 [-1 -3]
 [ 0 -2]
 [ 2 -2]]
거리를 각각 제곱 [[16  0]
 [ 9 25]
 [ 4  1]
 [ 1  9]
 [ 0  4]
 [ 4  4]]
제곱들을 더해 제곱근(직선거리) [4.         5.83095189 2.23606798 3.16227766 2.         2.82842712]
가장 가까이 배치되어야할 순서 인덱스 [4 2 5 3 0 1]
['Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail']
결론: 나의 예측 Pass
['Pass' 'Fail' 'Pass']


#### np.bincount() : 정수데이터의 0부터 최대값까지의 빈도수
#### np.unique(문자/정수배열, return_counts=True) 하면 문자열 빈도수 나옴( 이때 return_counts=True를 해야한다)

In [138]:
# 범위를 넓혀 가장 가까운 3개를 추출해서 응용
uql, uqc = np.unique(구분[sort_index][:3], return_counts=True)
print(uql)
print(uqc)

uql[np.argmax(uqc)]  # 빈도수가 높은 글자

['Fail' 'Pass']
[1 2]


'Pass'

In [132]:
arr4 = np.array([3,1,9,3])
np.bincount(arr4)

array([0, 1, 0, 2, 0, 0, 0, 0, 0, 1], dtype=int64)